server:
  port: 111
spring:
  application:
    name: dandelion-cron
  cloud:
    nacos:
      server-addr: xxx
  datasource:
    druid:
      url: jdbc:mysql://***?serverTimezone=UTC&characterEncoding=utf8
      username: abc
      password: abc
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
xxl:
  job:
    admin:
      addresses: http://xxx/xxl-job-admin
      username: xxx
      password: xxx
    executor:
      appname: dandelion-cron
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      address:
      ip:
      port: 111
      jobHandlerName: cronHandler
    accessToken: default_token
logging:
  config: classpath:logback.xml