server:
  port: 111
spring:
  application:
    name: dandelion-web
  profiles:
    active: dev
  datasource:
    druid:
      url: jdbc:mysql://xxx?serverTimezone=UTC&characterEncoding=utf8
      username: xxx
      password: xxx
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  redis:
    host: xxx
    port: 111
    password: xxx
    lettuce:
      pool:
        max-active: 8
        max-wait: 100
        max-idle: 1
        min-idle: 2
  cloud:
    nacos:
      server-addr: xxx
dandelion:
  web:
    admin:
      host: xxx
    upload:
      crowd:
        path: xxx