server:
  port: 111
spring:
  application:
    name: dandelion-handler
  profiles:
    active: dev
  datasource:
    druid:
      url: jdbc:mysql://xxx?serverTimezone=UTC&characterEncoding=utf8
      username: xxx
      password: xxx
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  redis:
    host: xxx
    port: 111
    password: xxx
    lettuce:
      pool:
        max-active: 8
        max-wait: 100
        max-idle: 1
        min-idle: 2
  rabbitmq:
    host: xxx
    port: 111
    virtual-host: /
    username: xxx
    password: xxx
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
      retry:
        enabled: true
        initial-interval: 1000
        multiplier: 2
        max-attempts: 3
  cloud:
    nacos:
      discovery:
        namespace: xxx
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml